apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "codeservergo.fullname" . }}
  labels:
    {{- include "codeservergo.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "codeservergo.namespace" . }}
spec:
  selector:
    matchLabels:
      {{- include "codeservergo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "codeservergo.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8080", "/root/go"]
        env:
        - name: PASSWORD
          value: {{ .Values.password }}
