apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: eventrouter
  name: {{ template "venti-stack.eventrouter.fullname" . }}
rules:
- apiGroups: 
  - ""
  resources:
  - events
  verbs:
  - get
  - watch
  - list

