apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
  name: {{ template "eventrouter.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
data:
  config.json: |
    {"sink": "stdout"}
