apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "venti-stack.eventrouter.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
data:
  config.json: |
    {"sink": "stdout"}
