{{- if .Values.eventrouter.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
  name: {{ template "eventrouter.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eventrouter.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eventrouter.labels" . | nindent 8 }}
    spec:
      {{- with .Values.eventrouter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "eventrouter.fullname" . }}
      {{- with .Values.eventrouter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ include "eventrouter.imageRepository" . }}/eventrouter:v0.4.10
        name: eventrouter
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
{{- end -}}
