apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
  name: {{ template "venti-stack.eventrouter.fullname" . }}
  namespace: {{ include "venti-stack.namespace" . }}
