apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lethe.fullname" . }}
  namespace: {{ template "logmon.namespace" . }}
  labels:
    {{- include "lethe.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "lethe.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lethe.labels" . | nindent 8 }}
    spec:
      containers:
      - name: reader
        image: {{ include "lethe.imageRepository" . }}/lethe:v0.2.1
        resources:
          {{- toYaml .Values.lethe.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /app/etc
        - name: storage-volume
          mountPath: /data
      - name: writer
        image: {{ index .Values "fluent-bit" "image" "repository" }}:2.1.4
        resources:
          {{- toYaml .Values.lethe.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /fluent-bit/etc
        - name: storage-volume
          mountPath: /data
    {{- if .Values.lethe.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.lethe.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.lethe.hostAliases }}
      hostAliases:
{{ toYaml .Values.lethe.hostAliases | indent 8 }}
    {{- end }}
    {{- if .Values.lethe.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.lethe.dnsConfig | indent 8 }}
    {{- end }}
    {{- if .Values.lethe.tolerations }}
      tolerations:
{{ toYaml .Values.lethe.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.lethe.affinity }}
      affinity:
{{ toYaml .Values.lethe.affinity | indent 8 }}
    {{- end }}
    {{- with .Values.lethe.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.lethe.terminationGracePeriodSeconds }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ if .Values.lethe.configMapOverrideName }}{{ .Release.Name }}-{{ .Values.lethe.configMapOverrideName }}{{- else }}{{ template "lethe.fullname" . }}{{- end }}
        - name: storage-volume
        {{- if .Values.lethe.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.lethe.persistentVolume.existingClaim }}{{ .Values.lethe.persistentVolume.existingClaim }}{{- else }}{{ template "lethe.fullname" . }}{{- end }}
        {{- else }}
          emptyDir:
          {{- if .Values.lethe.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.lethe.emptyDir.sizeLimit }}
          {{- else }}
            {}
          {{- end -}}
        {{- end -}}