kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "logmon.fullname" . }}-lethe
  namespace: {{ template "logmon.namespace" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.lethe.persistence.size }}
