apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-lethe
  namespace: kube-system
data:
  lethe.lua: |
    function audit(tag, timestamp, r)
      local u = string.sub(r["stageTimestamp"],1,19).."Z"
      return 1, timestamp, {tag=string.format("audit/audit/%s_%s.log",string.sub(u,1,10),string.sub(u,12,13)),
      row=string.format("%s %s",u,r["log"])}
    end
    function kube(tag, timestamp, r)
      local u = os.date("%Y-%m-%dT%H:%M:%SZ")
      return 1, timestamp, {tag=string.format("pod/%s/%s_%s.log",r["kubernetes"]["namespace_name"],string.sub(u,1,10),string.sub(u,12,13)),
      row=string.format("%s[%s|%s|%s] %s",u,r["kubernetes"]["namespace_name"],r["kubernetes"]["pod_name"],r["kubernetes"]["container_name"],r["log"])}
    end
    function host(tag, timestamp, r)
      local u = os.date("%Y-%m-%dT%H:%M:%SZ")
      return 1, timestamp, {tag=string.format("node/%s/%s_%s.log",r["_HOSTNAME"],string.sub(u,1,10),string.sub(u,12,13)),
      row=string.format("%s[%s|%s] %s",u,r["_HOSTNAME"],r["SYSLOG_IDENTIFIER"],r["MESSAGE"])}
    end
  parsers.conf: |
    [PARSER]
        Name    json
        Format  json
  fluent-bit.conf: |
    [SERVICE]
        Daemon              Off
        Flush               1
        Log_Level           info
        Parsers_File        parsers.conf
        HTTP_Server         On
        HTTP_Listen         0.0.0.0
        HTTP_Port           2020
        Health_Check        On
    [INPUT]
        Name                tail
        Tag                 raw
        Path                /var/log/kubernetes/audit.log
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
    [FILTER]
        Name                parser
        Match               raw
        Key_Name            log
        Parser              json
        Preserve_Key        On
        Reserve_Data        On
    [FILTER]
        Name                lua
        Match               raw
        script              lethe.lua
        call                audit
    [INPUT]
        Name                tail
        Path                /var/log/containers/*.log
        multiline.parser    docker, cri
        Tag                 kube.*
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
    [FILTER]
        Name                lua
        Match               kube.*
        script              lethe.lua
        call                kube
    
    [INPUT]
        Name                systemd
        Tag                 host.*
        Systemd_Filter      _SYSTEMD_UNIT=containerd.service
        Systemd_Filter      _SYSTEMD_UNIT=etcd.service
        Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail      On
    [FILTER]
        Name                lua
        Match               host.*
        script              lethe.lua
        call                host
    
    [FILTER]
        Name                rewrite_tag
        Match_Regex         ^(raw|kube|host)
        Rule                $tag .* $tag false
        Emitter_Name        re_emitted
    [FILTER]
        Name                modify
        Match_Regex         ^(audit|pod|node)
        Remove              tag
    [OUTPUT]
        Name                forward
        Match               *
        Host                lethe
        Port                24224
