---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit-lethe
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit-lethe
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentbit-lethe
subjects:
- kind: ServiceAccount
  name: fluentbit-lethe
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit-lethe
  namespace: kube-system
