apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
  name: {{ template "eventrouter.fullname" . }}
  namespace: {{ include "logmon.namespace" . }}
