apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "lethe.labels" . | nindent 4 }}
    {{- with .Values.lethe.extraConfigmapLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "venti-stack.lethe.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
data:
  lethe.yaml: |
    retention:
      size: {{ .Values.lethe.retention.size }}
      time: {{ .Values.lethe.retention.time }}
    storage:
      driver: filesystem
      log_data_path: /data/log
  fluent-bit.conf: |
    [SERVICE]
        Daemon       Off
        Flush        1
        Log_Level    info
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        Health_Check On
    [INPUT]
        Name         forward
        Listen       0.0.0.0
        Port         24224
    [OUTPUT]
        Name file
        Match *
        Path /data/log
        Mkdir true
        Format template
        Template {row}
