apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "lethe.labels" . | nindent 4 }}
  name: {{ template "lethe.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "lethe.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lethe.labels" . | nindent 8 }}
    spec:
      {{- with .Values.lethe.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lethe.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: reader
        image: {{ include "lethe.imageRepository" . }}/lethe:v0.2.1
        resources:
          {{- toYaml .Values.lethe.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /app/etc
        - name: storage-volume
          mountPath: /data
      - name: writer
        image: {{ index .Values "fluent-bit" "image" "repository" }}:2.1.4
        resources:
          {{- toYaml .Values.lethe.resources | nindent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /fluent-bit/etc
        - name: storage-volume
          mountPath: /data
      volumes:
        - name: config-volume
          configMap:
            name: {{ if .Values.lethe.configMapOverrideName }}{{ .Release.Name }}-{{ .Values.lethe.configMapOverrideName }}{{- else }}{{ template "lethe.fullname" . }}{{- end }}
        - name: storage-volume
        {{- if .Values.lethe.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.lethe.persistentVolume.existingClaim }}{{ .Values.lethe.persistentVolume.existingClaim }}{{- else }}{{ template "lethe.fullname" . }}{{- end }}
        {{- else }}
          emptyDir:
          {{- if .Values.lethe.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.lethe.emptyDir.sizeLimit }}
          {{- else }}
            {}
          {{- end -}}
        {{- end -}}