{{- if .Values.lethe.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lethe.serviceAccountName" . }}
  labels:
    {{- include "lethe.labels" . | nindent 4 }}
  {{- with .Values.lethe.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "venti-stack.namespace" . }}
automountServiceAccountToken: {{ .Values.lethe.automountServiceAccountToken }}
{{- end -}}
