apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit-lethe
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: fluentbit-lethe
  template:
    metadata:
      labels:
        app: fluentbit-lethe
    spec:
      serviceAccountName: fluentbit-lethe
      terminationGracePeriodSeconds: 0
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - image: {{ include "fluentBit.imageRepository" . }}/fluent-bit:1.9.3
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: fluent-bit
        ports:
        - containerPort: 2020
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
        volumeMounts:
        - mountPath: /fluent-bit/etc/
          name: config
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/machine-id
          name: etcmachineid
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: fluentbit-lethe
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File
