apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "venti.labels" . | nindent 4 }}
  name: {{ template "venti.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
