apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "venti.labels" . | nindent 4 }}
  name: {{ template "venti.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "venti.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "venti.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
