apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: venti
  name: {{ template "venti-stack.venti.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
