apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "venti.labels" . | nindent 4 }}
  name: {{ template "venti.fullname" .}}-alertrules
  namespace: {{ template "venti-stack.namespace" .}}
data:
{{- if .Values.venti.config.alerting }}
{{ toYaml .Values.venti.config.alerting | indent 2 }}
{{- end }}