{{- if .Values.venti.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "venti.labels" . | nindent 4 }}
  name: {{ template "venti.fullname" .}}-alertrules
  namespace: {{ template "venti-stack.namespace" .}}
data:
{{- if .Values.venti.config.alertRules.defaultGroups.enabled }}
  defaultGroups.yml: |
    commonLabels:
      rulefile: defaultGroups.yml
    datasourceSelector:
      type: prometheus
      system: main
    groups:
    {{- if .Values.venti.config.alertRules.defaultGroups.kubernetes.enabled }}
    - name: kubernetes
      rules:
      {{- range .Values.venti.config.alertRules.defaultGroups.kubernetes.rules }}
      {{- if .enabled }}
      - alert: {{.alert}}
        expr: {{.expr}}
        for: {{.for}}
        labels:
          severity: {{.severity}}
        annotations:
          summary: {{.summary}}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.venti.config.alertRules.defaultGroups.node.enabled }}
    - name: node
      rules:
      {{- range .Values.venti.config.alertRules.defaultGroups.node.rules }}
      {{- if .enabled }}
      - alert: {{.alert}}
        expr: {{.expr}}
        for: {{.for}}
        labels:
          severity: {{.severity}}
        annotations:
          summary: {{.summary}}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.venti.config.alertRules.defaultGroups.prometheus.enabled }}
    - name: prometheus
      rules:
      {{- range .Values.venti.config.alertRules.defaultGroups.prometheus.rules }}
      {{- if .enabled }}
      - alert: {{.alert}}
        expr: {{.expr}}
        for: {{.for}}
        labels:
          severity: {{.severity}}
        annotations:
          summary: {{.summary}}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.venti.config.alertRules.defaultGroups.vcustom.enabled }}
    - name: vcustom
      rules:
      {{- range .Values.venti.config.alertRules.defaultGroups.vcustom.rules }}
      {{- if .enabled }}
      - alert: {{.alert}}
        expr: {{.expr}}
        for: {{.for}}
        labels:
          severity: {{.severity}}
        annotations:
          summary: {{.summary}}
      {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
{{- if .Values.venti.config.alertRules.extraGroups }}
  extraGroups.yml: |
    datasourceSelector:
      type: prometheus
      system: main
    groups:
    {{- range .Values.venti.config.alertRules.extraGroups }}
    - name: {{.name}}
      rules:
      {{- range .rules }}
      - alert: {{.alert}}
        expr: {{.expr}}
        for: {{.for}}
        labels:
          severity: {{.severity}}
        annotations:
          summary: {{.summary}}
      {{- end }}
    {{- end }}
{{- end }}
{{- end -}}
