apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "venti.labels" . | nindent 4 }}
  name: {{ template "venti.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
data:
  alerting.yml: |
    alertings:
{{ toYaml .Values.venti.config.alertings | indent 6 }}
  datasources.yml: |
    datasources:
{{ toYaml .Values.venti.config.datasources | indent 6 }}
    discovery:
{{ toYaml .Values.venti.config.discovery | indent 6 }}
  users.yml: |
    users:
{{ toYaml .Values.venti.config.users | indent 6 }}
