apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "venti.labels" . | nindent 4 }}
  name: {{ template "venti.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
data:
  alerting.yml: |
    alerting:
      evaluation_interval: {{ .Values.venti.config.alerting.evaluationInterval }}
      alertmanagers:
      - static_configs:
        - targets:
          - http://{{ template "prometheus.alertmanager.fullname" .Subcharts.prometheus }}:9093
      globalLabels:
{{- with .Values.venti.config.alerting.globalLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
  datasources.yml: |
    datasources:
{{- if .Values.venti.config.datasources }}
{{ toYaml .Values.venti.config.datasources | indent 6 }}
{{- else }}
    - name: prometheus
      type: prometheus
      url: http://{{ template "prometheus.server.fullname" .Subcharts.prometheus }}
    - name: lethe
      type: lethe
      url: http://{{ template "lethe.fullname" . }}
{{- end }}
    discovery:
{{ toYaml .Values.venti.config.discovery | indent 6 }}
  users.yml: |
    users:
{{- if .Values.venti.config.users }}
{{ toYaml .Values.venti.config.users | indent 6 }}
{{- else }}
    - username: admin
      hash: $2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG
      isAdmin: true
{{- end }}
