apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "venti.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
data:
  alerting.yml: |
    alertings:
    - name: alertmanager
      type: alertmanager
      url: http://alertmanager:9093
  datasources.yml: |
    datasources:
    - name: prometheus
      type: prometheus
      url: http://venti-stack-prometheus-server
    - name: lethe
      type: lethe
      url: http://venti-stack-lethe:6060
  users.yml: |
    users:
    - username: admin
      hash: $2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG
      isAdmin: true
