apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "venti-stack.venti.fullname" . }}
  namespace: {{ template "venti-stack.namespace" . }}
  labels:
    {{- include "venti.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "venti.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "venti.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "venti-stack.venti.fullname" . }}
      containers:
      - name: venti
        image: {{ include "venti.imageRepository" . }}/venti:v0.2.2
        resources:
          requests:
            memory: 32Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 1000m
        ports:
        - containerPort: 3030
        volumeMounts:
        - name: config-volume
          mountPath: /app/etc
        - name: dashboards-volume
          mountPath: /app/etc/dashboards/common
        - name: user-dashboards-volume
          mountPath: /app/etc/dashboards/user
        - name: alertrules-volume
          mountPath: /app/etc/alertrules
    {{- if .Values.venti.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.venti.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.venti.hostAliases }}
      hostAliases:
{{ toYaml .Values.venti.hostAliases | indent 8 }}
    {{- end }}
    {{- if .Values.venti.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.venti.dnsConfig | indent 8 }}
    {{- end }}
    {{- if .Values.venti.tolerations }}
      tolerations:
{{ toYaml .Values.venti.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.venti.affinity }}
      affinity:
{{ toYaml .Values.venti.affinity | indent 8 }}
    {{- end }}
    {{- with .Values.venti.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.venti.terminationGracePeriodSeconds }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "venti-stack.venti.fullname" . }}
      - name: dashboards-volume
        configMap:
          name: {{ template "venti-stack.venti.fullname" . }}-dashboards
      - name: user-dashboards-volume
        configMap:
          name: {{ template "venti-stack.venti.fullname" . }}-user-dashboards
          optional: true
      - name: alertrules-volume
        configMap:
          name: {{ template "venti-stack.venti.fullname" . }}-alertrules
          optional: true
