apiVersion: v2
name: lethe-stack
appVersion: v0.3.0
version: 0.2.0
kubeVersion: ">=1.16.0-0"
description: Lethe stack is a logging system.
home: https://kuoss.github.io/helm-charts
icon: https://avatars.githubusercontent.com/u/110170011?s=400.png
sources:
  - https://github.com/fluent/fluent-bit
  - https://github.com/kuoss/eventrouter
  - https://github.com/kuoss/lethe
maintainers:
  - name: jmnote
    email: opcore@gmail.com
type: application
dependencies:
  - name: fluent-bit
    version: 0.48.8
    repository: https://fluent.github.io/helm-charts
    condition: fluent-bit.enabled
keywords:
  - lethe
  - logging
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/kuoss/helm-charts
  eventrouterVersion: v0.4.12
  fluentBitVersion: 3.2.7
