kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lethe
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.lethe.persistence.size }}
