apiVersion: v2
name: myip
appVersion: v0.1.6
version: 0.2.1
description: MyIP is a "What's my IP" application.
home: https://kuoss.github.io/helm-charts
icon: https://raw.githubusercontent.com/kuoss/docs/main/static/kuoss_logo.png
sources:
  - https://github.com/kuoss/myip
maintainers:
  - name: jmnote
    email: opcore@gmail.com
type: application
keywords:
  - xff
  - my-ip
  - real-ip
  - client-ip
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/kuoss/helm-charts
