apiVersion: v1
kind: ConfigMap
metadata:
  name: venti-config
  namespace: kube-system
data:
  datasources.yaml: |
    queryTimeOut: 30
    datasources:
    - type: Prometheus
      host: prometheus
    - type: Lethe
      host: lethe
  users.yaml: |
    users:
    - username: admin
      hash: $2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG
      isAdmin: true
