image:
  repository: ghcr.io/kuoss/code-server-go
  pullPolicy: IfNotPresent

deployment:
  annotations: {}

service:
  annotations: {}
  labels: {}
  type: ClusterIP
  servicePort: 8080
  loadBalancerIP: ""  # Assign ext IP when Service type is LoadBalancer
  loadBalancerSourceRanges: []  # Only allow access to loadBalancerIP from these IPs

  # Optionally specify extra list of additional ports exposed on the service
  extraPorts: []

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  extraLabels: {}
  hosts: []
  #   - code-server-go.domain.com
  #   - domain.com/code-server-go
  path: /
  pathType: Prefix
  extraPaths: []
  tls: []
  #  - secretName: code-server-go-tls
  #    hosts:
  #      - code-server-go.domain.com

password: kuoss
