image:
  repository: ghcr.io/kuoss/code-server-go
  pullPolicy: IfNotPresent

deployment:
  annotations: {}

service:
  annotations: {}
  labels: {}
  type: ClusterIP
  servicePort: 8080
  loadBalancerIP: ""  # Assign ext IP when Service type is LoadBalancer
  loadBalancerSourceRanges: []  # Only allow access to loadBalancerIP from these IPs

ingress:
  enabled: false
  annotations: {}
  extraLabels: {}
  hosts: []
  path: /
  pathType: Prefix
  extraPaths: []
  tls: []

password: kuoss
