apiVersion: v2
name: venti-stack
appVersion: v0.2.20
version: 0.2.9
kubeVersion: ">=1.16.0-0"
description: Venti stack is a logging and monitoring system.
home: https://kuoss.github.io/helm-charts
icon: https://avatars.githubusercontent.com/u/110170011?s=400.png
sources:
  - https://github.com/kubernetes/kube-state-metrics
  - https://github.com/kuoss/lethe
  - https://github.com/kuoss/venti
  - https://github.com/prometheus/alertmanager
  - https://github.com/prometheus/node_exporter
  - https://github.com/prometheus/prometheus
maintainers:
  - name: jmnote
    email: opcore@gmail.com
type: application
dependencies:
  - name: prometheus
    version: 25.11.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: fluent-bit
    version: 0.46.7
    # appVersion: 3.0.4
    repository: https://fluent.github.io/helm-charts
    condition: fluent-bit.enabled
keywords:
  - monitoring
  - prometheus
  - lethe
  - logging
  - venti
  - visualizer
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/kuoss/helm-charts
