{{- if .Values.eventrouter.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
  name: {{ template "eventrouter.fullname" . }}
rules:
- apiGroups: 
  - ""
  resources:
  - events
  verbs:
  - get
  - watch
  - list
{{- end -}}
