apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuoss-org
  namespace: venti-stack
spec:
  dnsNames:
  - kuoss.org
  - '*.kuoss.org'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tls-kuoss-org
