---
apiVersion: v1
kind: Namespace
metadata:
   name: logmon
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kuoss-org
  namespace: logmon
spec:
  dnsNames:
  - kuoss.org
  - '*.kuoss.org'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tls-kuoss-org
