
prometheus:
  alertmanager:
    ingress:
      enabled: true
      className: private
      hosts:
      - host: alertmanager.kuoss.org
        paths:
          - path: /
            pathType: ImplementationSpecific
      tls:
      - hosts:
        - alertmanager.kuoss.org
        secretName: tls-kuoss-org

  kube-state-metrics:
    collectors:
      - certificatesigningrequests
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - endpoints
      #- horizontalpodautoscalers
      - ingresses
      - jobs
      - leases
      - limitranges
      - mutatingwebhookconfigurations
      - namespaces
      - networkpolicies
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - poddisruptionbudgets
      - pods
      - replicasets
      - replicationcontrollers
      - resourcequotas
      - secrets
      - services
      - statefulsets
      - storageclasses
      - validatingwebhookconfigurations
      - volumeattachments

  server:
    retention: 15d
    extraFlags:
    - web.enable-lifecycle
    - storage.tsdb.retention.size=7GB
    persistentVolume:
      enabled: false
      size: 10Gi
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 800Mi
    ingress:
      enabled: true
      ingressClassName: private
      hosts:
      - prometheus.kuoss.org
      tls:
      - hosts:
        - prometheus.kuoss.org
        secretName: tls-kuoss-org

lethe:
  persistentVolume:
    size: 1Gi
  retention:
    time: 15d
    size: 500m
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 400m
      memory: 800Mi
  ingress:
    enabled: true
    ingressClassName: private
    hosts:
    - lethe.kuoss.org
    tls:
    - hosts:
      - lethe.kuoss.org
      secretName: tls-kuoss-org

venti:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 400m
      memory: 800Mi
  ingress:
    enabled: true
    ingressClassName: private
    hosts:
    - venti.kuoss.org
    tls:
    - hosts:
      - venti.kuoss.org
      secretName: tls-kuoss-org
