apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-annotator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress-annotator.labels" . | nindent 4 }}
data:
  rules: |
    {{- range $key, $value := .Values.rules }}
    {{ $key }}:
      {{- range $lineKey, $lineValue := $value }}
      {{ $lineKey }}: "{{ $lineValue }}"
      {{- end }}
    {{- end }}
