apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress-annotator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress-annotator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "ingress-annotator.selectorLabels" . | nindent 4 }}
