apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "logmon.fullname" . }}-venti
  namespace: {{ template "logmon.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venti
  template:
    metadata:
      labels:
        app: venti
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: venti
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: venti
        image: {{ include "venti.imageRepository" . }}/venti:v0.1.13
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 1000m
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: vol-config
          mountPath: /app/etc
        - name: vol-common-dashboards
          mountPath: /app/etc/dashboards/common
        - name: vol-user-dashboards
          mountPath: /app/etc/dashboards/user
        - name: vol-alertrules
          mountPath: /app/etc/alertrules
      volumes:
      - name: vol-config
        configMap:
          name: venti-config
      - name: vol-common-dashboards
        configMap:
          name: venti-common-dashboards
      - name: vol-user-dashboards
        configMap:
          name: venti-user-dashboards
          optional: true
      - name: vol-alertrules
        configMap:
          name: venti-alertrules
          optional: true
