{{- if .Values.venti.ingress.enabled -}}
{{- $serviceName := include "venti.fullname" . }}
{{- $servicePort := .Values.venti.service.servicePort -}}
{{- $ingressPath := .Values.venti.ingress.path -}}
{{- $ingressPathType := .Values.venti.ingress.pathType -}}
{{- $extraPaths := .Values.venti.ingress.extraPaths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "venti.fullname" . }}
  namespace: {{ template "logmon.namespace" . }}
spec:
  {{- if .Values.venti.ingress.ingressClassName }}
  ingressClassName: {{ .Values.venti.ingress.ingressClassName }}
  {{- end -}}
{{- if .Values.venti.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.venti.ingress.tls) $ | indent 2 }}
{{- end }}
  rules:
  {{- range .Values.venti.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
{{ if $extraPaths }}
{{ toYaml $extraPaths | indent 10 }}
{{- end }}
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
  {{- end -}}
{{- end -}}