apiVersion: v1
kind: Service
metadata:
  name: {{ template "logmon.fullname" . }}-venti
  namespace: {{ template "logmon.namespace" . }}
spec:
  selector:
    app: venti
  ports:
  - name: http
    port: 8080
    targetPort: 8080