apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: "Prometheus"
  name: prometheus
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: prometheus
  sessionAffinity: None
  type: ClusterIP