apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myip.fullname" . }}
  labels:
    {{- include "myip.labels" . | nindent 4 }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "myip.namespace" . }}
spec:
  selector:
    matchLabels:
      {{- include "myip.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myip.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        {{- if .Values.proxies }}
        - name: APP_PROXIES
          value: {{ .Values.proxies }}
        {{- end}}
        ports:
        - containerPort: 80
