apiVersion: v1
kind: Service
metadata:
  name: {{ include "myip.fullname" . }}
  labels:
    {{- include "myip.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ include "myip.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := . }}
    - {{ $cidr }}
  {{- end }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.servicePort }}
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "myip.selectorLabels" . | nindent 4 }}
